SET SERVEROUTPUT 	ON
SET VERIFY OFF
SET ECHO			ON
SET TERMOUT 		OFF
SET FEEDBACK		OFF
SET HEADING			ON
SET ESCAPE			ON
SET LINESIZE 		10000;
SET PAGESIZE		9999;
SET trimspool on
set long 1000000000 longc 60000


SPOOL &2
BEGIN
  DBMS_OUTPUT.ENABLE(9999999);
  DBMS_OUTPUT.NEW_LINE();
  FOR REC IN (SELECT TABLE_NAME, COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME NOT LIKE 'BIN$%' AND TABLE_NAME NOT LIKE '%$%'  AND DATA_TYPE NOT LIKE 'BLOB' AND DATA_TYPE NOT LIKE 'NCLOB' AND DATA_TYPE NOT LIKE 'CLOB' AND DATA_TYPE NOT LIKE 'XMLTYPE' AND DATA_TYPE NOT LIKE 'LONG' AND DATA_TYPE NOT LIKE 'LONG RAW' AND DATA_TYPE_OWNER IS NULL ORDER BY TABLE_NAME ASC, COLUMN_NAME ASC)
  LOOP
  	DBMS_OUTPUT.PUT_LINE ('SELECT "'||REC.COLUMN_NAME ||'" FROM '||REC.TABLE_NAME||' where &3 ORDER BY "'||REC.COLUMN_NAME||'" ASC;');
  END LOOP;
  FOR REC IN (SELECT TABLE_NAME, COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME NOT LIKE 'BIN$%' AND TABLE_NAME NOT LIKE '%$%'  AND (DATA_TYPE = 'NCLOB' OR DATA_TYPE LIKE 'CLOB') ORDER BY TABLE_NAME ASC, COLUMN_NAME ASC)
  LOOP
  	DBMS_OUTPUT.PUT_LINE ('SELECT dbms_lob.substr( '||REC.COLUMN_NAME ||', 4000, 1 ) FROM '||REC.TABLE_NAME||' where &3;');
  END LOOP;
  FOR REC IN (SELECT TABLE_NAME, COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME NOT LIKE 'BIN$%' AND TABLE_NAME NOT LIKE '%$%'  AND (DATA_TYPE LIKE 'XMLTYPE') ORDER BY TABLE_NAME ASC, COLUMN_NAME ASC)
  LOOP
  	DBMS_OUTPUT.PUT_LINE ('SELECT ('||REC.TABLE_NAME||'."'||REC.COLUMN_NAME ||'").GetStringVal() as val FROM '||REC.TABLE_NAME||' where &3;');
  END LOOP;
  DBMS_OUTPUT.NEW_LINE();
END;
/
SPOOL OFF;


SPOOL &1

PROMPT *******************************************************************************DATENSAETZE*************************************************************************************;
PROMPT  ;
@&2
SPOOL OFF
