alter table TAB_INDEX add "col add ix 3" NUMBER(15) not null;
create index ADD_2COL_IX on TAB_INDEX ( COL_ADD_IX_1,COL_ADD_IX_2 ) parallel;
alter index ADD_2COL_IX noparallel;
create index ADD_1COL_IX on TAB_INDEX ( COL_ADD_IX_2 ) parallel;
alter index ADD_1COL_IX noparallel;
create index ADD_1COL_IX_STRING on TAB_INDEX ( "col add ix 3" ) parallel;
alter index ADD_1COL_IX_STRING noparallel;
create index MOD_ORDER_IX on TAB_INDEX ( COL_MOD_IX_2,COL_MOD_IX_1 ) parallel;
alter index MOD_ORDER_IX noparallel;
create index MOD_PARALLEL_IX on TAB_INDEX ( COL_MOD_IX_3 ) parallel;
create index MOD_PARALLEL_4_IX on TAB_INDEX ( COL_MOD_IX_4 ) parallel  4;
create index MOD_NOPARALLEL_IX on TAB_INDEX ( COL_MOD_IX_5 ) parallel;
alter index MOD_NOPARALLEL_IX noparallel;
create unique index MOD_UNIQUE_IX on TAB_INDEX ( COL_MOD_IX_6 ) parallel;
alter index MOD_UNIQUE_IX noparallel;
create index MOD_NOUNIQUE_IX on TAB_INDEX ( COL_MOD_IX_7 ) parallel;
alter index MOD_NOUNIQUE_IX noparallel;
create index MOD_LOGGING_IX on TAB_INDEX ( COL_MOD_IX_10 ) parallel;
alter index MOD_LOGGING_IX noparallel;
create index MOD_LOGGING_REVERSE_IX on TAB_INDEX ( COL_MOD_IX_11 ) nologging parallel;
alter index MOD_LOGGING_REVERSE_IX noparallel;
create index MOD_RENAME on TAB_INDEX ( COL_MOD_IX_12 ) parallel;
alter index MOD_RENAME noparallel;
