drop table TAB_AA_OLD_DUPLICATE_CONS_NAME;
alter table TAB_MIXED_NAME_1 drop constraint FK_MIXED_NAME_2;
alter table TAB_MIXED_NAME_1 drop constraint FK_MIXED_NAME_INTAB_1;
alter table TAB_MIXED_NAME_1 drop constraint FK_MIXED_NAME_INTAB_2;
alter table TAB_MIXED_NAME_2 drop constraint FK_MIXED_NAME_1;
alter table TAB_CHECK_NUMBER drop constraint CHECK_SIZE;
alter table TAB_CHECK_NUMBER drop constraint OLD_WRONG_NAME;
alter table TAB_CHECK_NUMBER add constraint CHECK_SIZE check (ID BETWEEN 1 AND 10000);
alter table TAB_CHECK_NUMBER add constraint WRONG_NAME check (ID BETWEEN 1 AND 99);
alter table TAB_CHECK_LIST_ELEMENTS drop constraint CHECK_VERSAND_LIST;
alter table TAB_CHECK_LIST_ELEMENTS add constraint CHECK_VERSAND_LIST check (VERSAND IN ('ABHOLUNG','POST','LUFTFRACHT'));
alter table TAB_CHECK_DISABLE drop constraint CHECK_NUMBER;
alter table TAB_CHECK_DISABLE add constraint CHECK_NUMBER check (BESTAND >= 0);
alter table TAB_CHECK_WRONG_COLUMN drop constraint CHECK_WRONG_COLUMN;
alter table TAB_CHECK_WRONG_COLUMN add constraint CHECK_WRONG_COLUMN check (ID BETWEEN 1 AND 500);
alter table TAB_CHECK_WRONG_DEFERRED drop constraint CHECK_DEFERRED;
alter table TAB_CHECK_WRONG_DEFERRED add constraint CHECK_DEFERRED check (BESTAND >= 0) deferrable initially deferred;
create table TAB_BB_NEW_DUPLICATE_CONS_NAME (  ID NUMERIC(5)   )  ;
alter table TAB_BB_NEW_DUPLICATE_CONS_NAME add constraint CHECK_DUPLICATE_CONS_NAME check (ID IS NOT NULL);
alter table TAB_CHECK_DROP drop constraint CHECK_DROPME;
alter table TAB_MIXED_NAME_1 add constraint FK_MIXED_NAME_1 check (ID BETWEEN 1 AND 500);
alter table TAB_MIXED_NAME_1 add constraint FK_MIXED_NAME_INTAB_1 check (ID BETWEEN 1 AND 501);
alter table TAB_MIXED_NAME_1 add constraint FK_MIXED_NAME_INTAB_2 check (ID BETWEEN 1 AND 502);
alter table TAB_MIXED_NAME_2 add constraint FK_MIXED_NAME_2 check (ID BETWEEN 1 AND 500);
