SET DEFINE OFF;
Insert into BUSINESS_PARTNERS
   (BPAR_ID, 
    VERSION, TYPE, STREET, CITY, STATE, 
    ZIPCODE, COUNTRY, EMAIL, FIRSTNAME, LASTNAME, 
    USERNAME, PASSWORD, STATUS, NAME, WEBSITE)
 Values
   (1, 0, 'Company A', 'Mystreet', 'Chicago', 
    NULL, '34565', 'US', 'x@y.z', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUSINESS_PARTNERS
   (BPAR_ID, 
    VERSION, TYPE, STREET, CITY, STATE, 
    ZIPCODE, COUNTRY, EMAIL, FIRSTNAME, LASTNAME, 
    USERNAME, PASSWORD, STATUS, NAME, WEBSITE)
 Values
   (3, 0, 'Company C', 'Mystreet', 'Berlin', 
    NULL, '34565', 'DE', 'x@y.z', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUSINESS_PARTNERS
   (BPAR_ID, 
    VERSION, TYPE, STREET, CITY, STATE, 
    ZIPCODE, COUNTRY, EMAIL, FIRSTNAME, LASTNAME, 
    USERNAME, PASSWORD, STATUS, NAME, WEBSITE)
 Values
   (2, 0, 'Company B', 'Mystreet', 'Paris', 
    NULL, '34565', 'FR', 'x@y.z', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL);
COMMIT;
