SET DEFINE OFF;
Insert into ORDERS
   (ORDR_ID, 
    VERSION, BPAR_ID, ORDERDATE, TRACKING_NUMBER, STATUS, 
    SHIPPING_STREET, SHIPPING_CITY, SHIPPING_STATE, SHIPPING_ZIPCODE, SHIPPING_COUNTRY)
 Values
   (1, 0, 1, TO_DATE('02/10/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), '423421', 
    '1', 'Mystreet', 'London', NULL, '312', 
    'GB');
COMMIT;
