create table tab_always alias alw
(
  col number(15) generated always as identity not null
);

create table tab_by_default alias def
(
  col number(15) generated by default as identity not null
);

create table tab_by_default_on_null alias defn
(
  col number(15) generated by default on null as identity not null
);

create table tab_parameter alias para
(
  col number(15) generated always as identity (increment by 10 maxvalue 1000 minvalue 30 nocycle cache 12 order) not null
);

create table tab_add_column alias addc
(
  other number(15),
  col number(15) generated always as identity not null
);

create table tab_add_identity alias addi
(
  col number(15) generated always as identity not null
);

create table tab_remove_identity alias remi
(
  col number(15) not null
);

create table tab_change_identity alias chng
(
  col number(15) generated always as identity not null
);



