create table tab_add_column
(
  other number(15)
);

create table tab_add_identity
(
  col number(15) not null
);

create table tab_remove_identity
(
  col number(15) generated always as identity not null
);

create table tab_change_identity
(
  col number(15) generated by default as identity not null
);
