Vagrant.configure("2") do |config|

  config.vm.box = "pframpton/centos-6.5-rvm-ruby"
  config.vm.network :forwarded_port, host: 4000, guest: 4000
  config.vm.provision :shell, path: "bootstrap.sh"
  # mount orcas directory to vm
  config.vm.synced_folder "..", "/orcas/orcas", create: true
end

