alter table TAB_DEL_CAS drop constraint FK_TAB_DEL_CAS_TAB_A_ID;
alter table TAB_DEL_CAS drop constraint FK_TAB_DEL_CAS_TAB_B_ID;
alter table TAB_DEL_CAS drop constraint FK_TAB_DEL_CAS_TAB_C_ID;
alter table TAB_NO_ACTION drop constraint FK_TAB_NO_ACTION_TAB_A_ID;
alter table TAB_NO_ACTION drop constraint FK_TAB_NO_ACTION_TAB_B_ID;
alter table TAB_NO_ACTION drop constraint FK_TAB_NO_ACTION_TAB_C_ID;
alter table TAB_SET_NULL drop constraint FK_TAB_SET_NULL_TAB_A_ID;
alter table TAB_SET_NULL drop constraint FK_TAB_SET_NULL_TAB_B_ID;
alter table TAB_SET_NULL drop constraint FK_TAB_SET_NULL_TAB_C_ID;
alter table TAB_WRONG_FK_NAME drop constraint FK_TAB_WRONG_FK_NAME;
alter table TAB_WRONG_FK_COLUMN drop constraint FK_TAB_WRONG_FK_COLUMN;
alter table TAB_WRONG_FK_COLUMN_ORDER drop constraint FK_TAB_WRONG_FK_COLUMN_ORDER;
alter table TAB_MIXED_NAME_1 drop constraint FK_MIXED_NAME_2;
alter table TAB_MIXED_NAME_1 drop constraint FK_MIXED_NAME_INTAB_1;
alter table TAB_MIXED_NAME_1 drop constraint FK_MIXED_NAME_INTAB_2;
alter table TAB_MIXED_NAME_2 drop constraint FK_MIXED_NAME_1;
alter table TAB_A drop constraint null;
alter table TAB_A add constraint PK_TAB_A primary key (TAB_A_ID);
alter table TAB_B drop constraint null;
alter table TAB_B add constraint PK_TAB_B primary key (TAB_B_ID);
alter table TAB_C drop constraint null;
alter table TAB_C add constraint PK_TAB_C primary key (TAB_C_ID);
create table TAB_D (  "tab d id" NUMBER(9) not null   )  ;
alter table TAB_D add constraint PK_TAB_D primary key ("tab d id");
alter table TAB_DEL_CAS add TAB_D_ID NUMBER(8);
create index FK_TAB_DEL_CAS_TAB_A_ID_GEN_IX on TAB_DEL_CAS ( TAB_A_ID ) parallel;
alter index FK_TAB_DEL_CAS_TAB_A_ID_GEN_IX noparallel;
create index FK_TAB_DEL_CAS_TAB_B_ID_GEN_IX on TAB_DEL_CAS ( TAB_B_ID ) parallel;
alter index FK_TAB_DEL_CAS_TAB_B_ID_GEN_IX noparallel;
create index FK_TAB_DEL_CAS_TAB_C_ID_GEN_IX on TAB_DEL_CAS ( TAB_C_ID ) parallel;
alter index FK_TAB_DEL_CAS_TAB_C_ID_GEN_IX noparallel;
create index FK_TAB_DEL_CAS_TAB_D_ID_GEN_IX on TAB_DEL_CAS ( TAB_D_ID ) parallel;
alter index FK_TAB_DEL_CAS_TAB_D_ID_GEN_IX noparallel;
alter table TAB_NO_ACTION add TAB_D_ID NUMBER(8);
create index FK_TAB_NO_ACTION_TAB_A__GEN_IX on TAB_NO_ACTION ( TAB_A_ID ) parallel;
alter index FK_TAB_NO_ACTION_TAB_A__GEN_IX noparallel;
create index FK_TAB_NO_ACTION_TAB_B__GEN_IX on TAB_NO_ACTION ( TAB_B_ID ) parallel;
alter index FK_TAB_NO_ACTION_TAB_B__GEN_IX noparallel;
create index FK_TAB_NO_ACTION_TAB_C__GEN_IX on TAB_NO_ACTION ( TAB_C_ID ) parallel;
alter index FK_TAB_NO_ACTION_TAB_C__GEN_IX noparallel;
create index FK_TAB_NO_ACTION_TAB_D__GEN_IX on TAB_NO_ACTION ( TAB_D_ID ) parallel;
alter index FK_TAB_NO_ACTION_TAB_D__GEN_IX noparallel;
alter table TAB_SET_NULL add TAB_D_ID NUMBER(8);
create index FK_TAB_SET_NULL_TAB_A_I_GEN_IX on TAB_SET_NULL ( TAB_A_ID ) parallel;
alter index FK_TAB_SET_NULL_TAB_A_I_GEN_IX noparallel;
create index FK_TAB_SET_NULL_TAB_B_I_GEN_IX on TAB_SET_NULL ( TAB_B_ID ) parallel;
alter index FK_TAB_SET_NULL_TAB_B_I_GEN_IX noparallel;
create index FK_TAB_SET_NULL_TAB_C_I_GEN_IX on TAB_SET_NULL ( TAB_C_ID ) parallel;
alter index FK_TAB_SET_NULL_TAB_C_I_GEN_IX noparallel;
create index FK_TAB_SET_NULL_TAB_D_I_GEN_IX on TAB_SET_NULL ( TAB_D_ID ) parallel;
alter index FK_TAB_SET_NULL_TAB_D_I_GEN_IX noparallel;
alter table TAB_2_COLUMN_PK drop constraint PK_TAB_2_COLUMN_PK;
alter table TAB_2_COLUMN_PK modify ( ID1 not null );
alter table TAB_2_COLUMN_PK modify ( ID2 not null );
alter table TAB_2_COLUMN_PK add constraint PK_TAB_2_COLUMN_PK primary key (ID1,ID2);
create index FK_TAB_RIGHT_FK_NAME_GEN_IX on TAB_WRONG_FK_NAME ( ID ) parallel;
alter index FK_TAB_RIGHT_FK_NAME_GEN_IX noparallel;
create index FK_TAB_WRONG_FK_COLUMN_GEN_IX on TAB_WRONG_FK_COLUMN ( ID ) parallel;
alter index FK_TAB_WRONG_FK_COLUMN_GEN_IX noparallel;
create index FK_TAB_WRONG_FK_COLUMN__GEN_IX on TAB_WRONG_FK_COLUMN_ORDER ( ID1,ID2 ) parallel;
alter index FK_TAB_WRONG_FK_COLUMN__GEN_IX noparallel;
create table TAB_WRONG_DEFERRED (  ID NUMBER(9)   )  ;
create index FK_TAB_RIGHT_DEFERRED_GEN_IX on TAB_WRONG_DEFERRED ( ID ) parallel;
alter index FK_TAB_RIGHT_DEFERRED_GEN_IX noparallel;
create index FK_MIXED_NAME_1_GEN_IX on TAB_MIXED_NAME_1 ( ID ) parallel;
alter index FK_MIXED_NAME_1_GEN_IX noparallel;
create index FK_MIXED_NAME_INTAB_1_GEN_IX on TAB_MIXED_NAME_1 ( ID_1 ) parallel;
alter index FK_MIXED_NAME_INTAB_1_GEN_IX noparallel;
create index FK_MIXED_NAME_INTAB_2_GEN_IX on TAB_MIXED_NAME_1 ( ID_2 ) parallel;
alter index FK_MIXED_NAME_INTAB_2_GEN_IX noparallel;
create index FK_MIXED_NAME_2_GEN_IX on TAB_MIXED_NAME_2 ( ID ) parallel;
alter index FK_MIXED_NAME_2_GEN_IX noparallel;
create table TAB_INDEX_TEST (  TAB_INDEX_TEST_ID NUMBER(9) not null   )  ;
alter table TAB_INDEX_TEST add constraint PK_TAB_INDEX_TEST primary key (TAB_INDEX_TEST_ID);
create table TAB_INDEX_TEST_REF (  TAB_A_ID NUMBER(9), TAB_B_ID NUMBER(9)   )  ;
alter table TAB_INDEX_TEST_REF add constraint UK_TAB_A_B_ID unique (TAB_A_ID,TAB_B_ID);
alter table TAB_DEL_CAS add constraint FK_TAB_DEL_CAS_TAB_A_ID foreign key (TAB_A_ID) references TAB_A(TAB_A_ID) on delete cascade;
alter table TAB_DEL_CAS add constraint FK_TAB_DEL_CAS_TAB_B_ID foreign key (TAB_B_ID) references TAB_B(TAB_B_ID) on delete cascade;
alter table TAB_DEL_CAS add constraint FK_TAB_DEL_CAS_TAB_C_ID foreign key (TAB_C_ID) references TAB_C(TAB_C_ID) on delete cascade;
alter table TAB_DEL_CAS add constraint FK_TAB_DEL_CAS_TAB_D_ID foreign key (TAB_D_ID) references TAB_D("tab d id") on delete cascade;
alter table TAB_NO_ACTION add constraint FK_TAB_NO_ACTION_TAB_A_ID foreign key (TAB_A_ID) references TAB_A(TAB_A_ID);
alter table TAB_NO_ACTION add constraint FK_TAB_NO_ACTION_TAB_B_ID foreign key (TAB_B_ID) references TAB_B(TAB_B_ID);
alter table TAB_NO_ACTION add constraint FK_TAB_NO_ACTION_TAB_C_ID foreign key (TAB_C_ID) references TAB_C(TAB_C_ID);
alter table TAB_NO_ACTION add constraint FK_TAB_NO_ACTION_TAB_D_ID foreign key (TAB_D_ID) references TAB_D("tab d id");
alter table TAB_SET_NULL add constraint FK_TAB_SET_NULL_TAB_A_ID foreign key (TAB_A_ID) references TAB_A(TAB_A_ID) on delete set null;
alter table TAB_SET_NULL add constraint FK_TAB_SET_NULL_TAB_B_ID foreign key (TAB_B_ID) references TAB_B(TAB_B_ID) on delete set null;
alter table TAB_SET_NULL add constraint FK_TAB_SET_NULL_TAB_C_ID foreign key (TAB_C_ID) references TAB_C(TAB_C_ID) on delete set null;
alter table TAB_SET_NULL add constraint FK_TAB_SET_NULL_TAB_D_ID foreign key (TAB_D_ID) references TAB_D("tab d id") on delete set null;
alter table TAB_WRONG_FK_NAME add constraint FK_TAB_RIGHT_FK_NAME foreign key (ID) references TAB_A(TAB_A_ID);
alter table TAB_WRONG_FK_COLUMN add constraint FK_TAB_WRONG_FK_COLUMN foreign key (ID) references TAB_B(TAB_B_ID);
alter table TAB_WRONG_FK_COLUMN_ORDER add constraint FK_TAB_WRONG_FK_COLUMN_ORDER foreign key (ID1,ID2) references TAB_2_COLUMN_PK(ID1,ID2);
alter table TAB_WRONG_DEFERRED add constraint FK_TAB_RIGHT_DEFERRED foreign key (ID) references TAB_A(TAB_A_ID) deferrable initially  deferred;
alter table TAB_MIXED_NAME_1 add constraint FK_MIXED_NAME_1 foreign key (ID) references TAB_A(TAB_A_ID);
alter table TAB_MIXED_NAME_1 add constraint FK_MIXED_NAME_INTAB_1 foreign key (ID_1) references TAB_A(TAB_A_ID);
alter table TAB_MIXED_NAME_1 add constraint FK_MIXED_NAME_INTAB_2 foreign key (ID_2) references TAB_B(TAB_B_ID);
alter table TAB_MIXED_NAME_2 add constraint FK_MIXED_NAME_2 foreign key (ID) references TAB_A(TAB_A_ID);
alter table TAB_INDEX_TEST_REF add constraint FK_TAB_INDEX_TEST_REF_A_ID foreign key (TAB_A_ID) references TAB_INDEX_TEST(TAB_INDEX_TEST_ID) on delete cascade;
