-- ignore-additionsonly: drop table TAB_OLD;
create table TAB_NEW (  ID NUMBER(5)   )  ;
alter table TAB_NEW add constraint TAB_NEW_CHECK_SIZE check (ID BETWEEN 1 AND 10000);
alter table TAB_CHG drop constraint TAB_CHG_CHECK_SIZE_CHG;
alter table TAB_CHG drop constraint TAB_CHG_CHECK_SIZE_OLD;
alter table TAB_CHG add ID_ADD NUMBER(5);
-- ignore-additionsonly: alter table TAB_CHG add constraint TAB_CHG_CHECK_SIZE check (ID BETWEEN 1 AND 900);
-- ignore-additionsonly: alter table TAB_CHG add constraint TAB_CHG_CHECK_SIZE_NEW check (ID BETWEEN 1 AND 99);
alter table TAB_CHG add constraint TAB_CHG_CHECK_SIZE_NEW_COL check (id_add BETWEEN 1 AND 99);
-- ignore-additionsonly: alter table TAB_CHG add constraint TAB_CHG_CHECK_SIZE_NEW_COL_NOT_NULL check (id_add not null);
