alter table TAB_DEL_COL drop constraint DEL_FK_SINGLE;
alter table TAB_DEL_COL drop constraint DEL_FK_MULTI;
alter table TAB_DEL_COL drop constraint DEL_FK_MULTI_OLD;
alter table TAB_DEL_COL drop constraint DEL_FK_SINGLE_DROP_TAB;
drop table AAA_TAB_DROP;
alter table TAB_INS_COL add CHG_COL_ADD_NOT_NULL NUMERIC(15);
alter table TAB_INS_COL add CHG_COL_ADD_DEFAULT NUMERIC(15);
alter table TAB_DEL_COL drop constraint null;
alter table TAB_DEL_COL drop constraint DEL_CHECK_SINGLE;
alter table TAB_DEL_COL drop constraint DEL_CHECK_MULTI;
alter table TAB_DEL_COL drop constraint DEL_CHECK_MULTI_OLD;
alter table TAB_DEL_COL drop constraint DEL_UK_SINGLE;
alter table TAB_DEL_COL drop constraint DEL_UK_MULTI;
alter table TAB_DEL_COL drop constraint DEL_UK_MULTI_OLD;
alter table TAB_DEL_COL drop column PKCOL;
alter table TAB_DEL_COL drop column COL_DEFAULT;
alter table TAB_DEL_COL drop column COL_NOT_NULL;
alter table TAB_DEL_COL drop column COL_NOT_NULL_DEFAULT;
alter table TAB_DEL_COL_NOCOMBINE drop constraint DEL_CHECK_NOCOMBINE;
alter table TAB_DEL_COL_NOCOMBINE drop column COL_DROP;
alter table TAB_DEL_COL_NOCOMBINE add COL_NEW NUMERIC(15);
alter table TAB_DEL_COL_NOCOMBINE add constraint COL_NEW_CONS check (col_new in (id,8));
alter table TAB_MAX_COMBINE parallel 2;
alter table TAB_MAX_COMBINE drop constraint MOD_CHECK;
alter table TAB_MAX_COMBINE drop constraint DEL_CHECK;
alter table TAB_MAX_COMBINE drop constraint DEL_UK;
alter table TAB_MAX_COMBINE add COL_ADD NUMERIC(15);
alter table TAB_MAX_COMBINE add constraint ADD_CHECK check (col_add in (col_drop_c,7));
alter table TAB_MAX_COMBINE add constraint MOD_CHECK check (col_drop_c in (id,8)) deferrable initially deferred;
alter table TAB_MAX_COMBINE add constraint ADD_UK unique (COL_ADD,COL_DROP_C);
