create table auto_increment_demo
(
  id         number(19)  generated by default on null as identity   not null,
  version    number(15)  default "0"                                not null,

  primary key(id)
);


