alter table TAB_FK_REF_UK drop constraint FK_TAB_UK_ID;
alter table TAB_UK drop constraint TAB_WRONG_PK_REVERSE;
alter table TAB_UK drop (TAB_B_DATEN);
alter table TAB_UK modify ( TAB_A_ID not null );
alter table TAB_UK add TAB_A_DATEN VARCHAR2(20);
alter table TAB_UK add constraint TAB_WRONG_PK_REVERSE primary key (TAB_A_ID) using index reverse;
create index FK_TAB_UK_ID_GEN_IX on TAB_FK_REF_UK ( TAB_B_ID ) parallel;
alter index FK_TAB_UK_ID_GEN_IX noparallel;
create index FK_TAB_REF_UK_GEN_IX on TAB_FK_REF_UK ( TAB_B_ID,TAB_B_BEZEICHNER ) parallel;
alter index FK_TAB_REF_UK_GEN_IX noparallel;
create table TAB_FK_REF_UK_UK (  TAB_B_ID NUMBER(9), TAB_B_BEZEICHNER VARCHAR2(10), TAB_B_DATEN VARCHAR2(20)   )  ;
alter table TAB_FK_REF_UK_UK add constraint UK_TAB_REF_UK_UK unique (TAB_B_ID,TAB_B_BEZEICHNER);
alter table TAB_COMMENT add DTN_TAB_COMMENT NUMBER(9);
update TAB_COMMENT set DTN_TAB_COMMENT = TAB_COMMENT;
commit;
alter table TAB_COMMENT rename column TAB_COMMENT to DTO_TAB_COMMENT;
alter table TAB_COMMENT rename column DTN_TAB_COMMENT to TAB_COMMENT;
alter table TAB_COMMENT drop column DTO_TAB_COMMENT;
comment on column TAB_COMMENT . TAB_COMMENT is 'xy';
alter table TAB_FK_REF_UK add constraint FK_TAB_UK_ID foreign key (TAB_B_ID) references TAB_UK(TAB_A_ID);
alter table TAB_FK_REF_UK_UK add constraint FK_TAB_REF_UK_UK foreign key (TAB_B_ID,TAB_B_BEZEICHNER) references TAB_UK(TAB_A_ID,TAB_A_BEZEICHNER);
