drop table TAB_DEL;
create table TAB_NEW (  ID NUMERIC(15) not null, COL_DEFAULT NUMERIC(15) default 66, COL_NOT_NULL NUMERIC(15) not null, COL_NOT_NULL_DEFAULT NUMERIC(15) default 66 not null   )  ;
alter table TAB_INS_COL modify column CHG_COL_ADD_NOT_NULL NUMERIC(15) not null;
alter table TAB_INS_COL modify column CHG_COL_ADD_DEFAULT NUMERIC(15) default 33;
alter table TAB_INS_COL modify column CHG_COL_ADD_DEFAULT_NOT_NULL NUMERIC(15) default 44 not null;
alter table TAB_INS_COL modify column CHG_COL_DEL_DEFAULT NUMERIC(15);
alter table TAB_INS_COL modify column CHG_COL_DEL_NOT_NULL NUMERIC(15);
alter table TAB_INS_COL modify column CHG_COL_INC_PRECISION NUMERIC(15);
alter table TAB_INS_COL modify column CHG_COL_INC_SCALE NUMERIC(15,10);
alter table TAB_INS_COL add NEW_COL_DEFAULT NUMERIC(15) default 11;
alter table TAB_INS_COL add NEW_COL_NOT_NULL NUMERIC(15) not null;
alter table TAB_INS_COL add NEW_COL_NOT_NULL_DEFAULT NUMERIC(15) default 22 not null;
alter table TAB_DEL_COL  drop COL_DEFAULT;
alter table TAB_DEL_COL  drop COL_NOT_NULL;
alter table TAB_DEL_COL  drop COL_NOT_NULL_DEFAULT;
