create table TAB_MOD_NEW (  COL_ADD_IX_1 NUMBER(15) not null   )  ;
alter table TAB_MOD_NEW add primary key (COL_ADD_IX_1);
create materialized view log on TAB_MOD_NEW with primary key purge immediate asynchronous;
drop materialized view log on TAB_MOD_IMMEDIATE;
create materialized view log on TAB_MOD_IMMEDIATE with primary key;
drop materialized view log on TAB_MOD_ASYNCHRONOUS;
create materialized view log on TAB_MOD_ASYNCHRONOUS with primary key purge immediate asynchronous;
create table TAB_MOD_SW_NEW (  COL_ADD_IX_1 NUMBER(15) not null   )  ;
alter table TAB_MOD_SW_NEW add primary key (COL_ADD_IX_1);
create materialized view log on TAB_MOD_SW_NEW with primary key purge start with to_date('31.10.14','dd.mm.yy');
drop materialized view log on TAB_MOD_SW;
create materialized view log on TAB_MOD_SW with primary key purge start with to_date('31.10.15','dd.mm.yy');
create table TAB_MOD_NSW_NEW (  COL_ADD_IX_1 NUMBER(15) not null   )  ;
alter table TAB_MOD_NSW_NEW add primary key (COL_ADD_IX_1);
create materialized view log on TAB_MOD_NSW_NEW with primary key purge start with to_date('31.10.14','dd.mm.yy') next to_date('30.11.14','dd.mm.yy');
drop materialized view log on TAB_MOD_NSW;
create materialized view log on TAB_MOD_NSW with primary key purge start with to_date('31.10.14','dd.mm.yy') next to_date('30.11.15','dd.mm.yy');
create table TAB_MOD_INT_NEW (  COL_ADD_IX_1 NUMBER(15) not null   )  ;
alter table TAB_MOD_INT_NEW add primary key (COL_ADD_IX_1);
create materialized view log on TAB_MOD_INT_NEW with primary key purge start with to_date('31.10.14','dd.mm.yy') repeat interval 3;
drop materialized view log on TAB_MOD_INT;
create materialized view log on TAB_MOD_INT with primary key purge start with to_date('31.10.14','dd.mm.yy') repeat interval 2;
