alter table TAB_NEW_PK add constraint TAB_NEW_PK primary key (ID);
alter table TAB_WRONG_PK_NAME drop primary key;
alter table TAB_WRONG_PK_NAME add constraint WRONG_PK_NAME primary key (ID);
alter table TAB_WRONG_PK_REVERSE drop primary key;
alter table TAB_WRONG_PK_REVERSE add constraint TAB_WRONG_PK_REVERSE primary key (ID) using index reverse;
alter table TAB_WRONG_PK_COLUMN drop primary key;
alter table TAB_WRONG_PK_COLUMN add constraint TAB_WRONG_PK_COLUMN primary key (ID1);
alter table TAB_WRONG_PK_COLUMN_ORDER drop primary key;
alter table TAB_WRONG_PK_COLUMN_ORDER add constraint TAB_WRONG_PK_COLUMN_ORDER primary key (ID1,ID2);
create table TAB_NONAME_PK (  ID1 NUMERIC(15) not null , primary key (ID1)  )  ;
create table TAB_CREATE_TAB_NAMED_PK (  ID1 NUMERIC(15) not null , primary key (ID1)  )  ;
create table TAB_NEW_PK_STRING (  "id string" NUMERIC(15) not null , primary key ("id string")  )  ;
