drop index MOD_1_IX;
create index ADD_1_IX on TAB_INDEX ( NVL(COL_1,1) ) parallel;
alter index ADD_1_IX noparallel;
create index ADD_2_IX on TAB_INDEX ( COL_1,COL_2,NVL(COL_1,1) ) parallel;
alter index ADD_2_IX noparallel;
create index ADD_3_IX on TAB_INDEX ( NVL(COL_1,1),COL_2 ) parallel;
alter index ADD_3_IX noparallel;
create index ADD_4_IX on TAB_INDEX ( NVL(TO_CHAR(COL_1),'test') ) parallel;
alter index ADD_4_IX noparallel;
create index MOD_1_IX on TAB_INDEX ( NVL(TO_CHAR(COL_2),'klein') ) parallel;
alter index MOD_1_IX noparallel;
drop index INLINE_MOD_1_IX;
create index INLINE_ADD_1_IX on TAB_INDEX_INLINE ( NVL(COL_1,1) ) parallel;
alter index INLINE_ADD_1_IX noparallel;
create index INLINE_ADD_2_IX on TAB_INDEX_INLINE ( COL_1,COL_2,NVL(COL_1,1) ) parallel;
alter index INLINE_ADD_2_IX noparallel;
create index INLINE_ADD_3_IX on TAB_INDEX_INLINE ( NVL(COL_1,1),COL_2 ) parallel;
alter index INLINE_ADD_3_IX noparallel;
create index INLINE_ADD_4_IX on TAB_INDEX_INLINE ( NVL(TO_CHAR(COL_1),'test') ) parallel;
alter index INLINE_ADD_4_IX noparallel;
create index INLINE_MOD_1_IX on TAB_INDEX_INLINE ( NVL(TO_CHAR(COL_2),'klein') ) parallel;
alter index INLINE_MOD_1_IX noparallel;
