@startuml

allowmixing

skinparam backgroundcolor transparent

database Oracle {
  class categories << (T,red) >> {
    #""ctgr_id        number(15)                  not null""
    #""version        number(15)      default 0   not null""
    #""name           varchar2(30)                not null""
    #""description    varchar2(1000)              not null""
    #""<back:LightBlue>image_location varchar2(1000)</back> ""
    ..
    -""constraint ctgr_pk primary key (ctgr_id)""
    -""constraint ctgr_uc unique (name)""
  }
}

@enduml
