@@create_table                  tab_create  ""  ""  ""  ""  ""  ""
@@alter_table_add_column        tab_create  id  number(15)  mandatory  ""  ""

@@create_table                  tab_ins_col  ""  ""  ""  ""  ""  ""
@@alter_table_add_column        tab_ins_col  id       number(15)  mandatory  ""  ""
@@alter_table_add_column        tab_ins_col  new_col  number(15)  mandatory  66  ""

@@create_table                  tab_del_col  ""  ""  ""  ""  ""  ""
@@alter_table_add_column        tab_del_col  id  number(15)  mandatory  ""  ""

@@create_table                  tab_mod_cols  ""  ""  ""  ""  ""  ""
@@alter_table_add_column        tab_mod_cols  col_chg_size          number(14)           mandatory  ""   ""
@@alter_table_add_column        tab_mod_cols  col_chg_precision     number(15,6)         mandatory  ""   ""
@@alter_table_add_column        tab_mod_cols  col_chg_type          varchar2(15)         mandatory  ""   ""
@@alter_table_add_column        tab_mod_cols  col_set_nullable      varchar2(15)         ""         ""   ""
@@alter_table_add_column        tab_mod_cols  col_set_not_nullable  varchar2(15)         mandatory  ""   ""
@@alter_table_add_column        tab_mod_cols  col_set_default       number(15)           ""         4    ""
@@alter_table_add_column        tab_mod_cols  col_chg_default       number(15)           ""         7    ""
@@alter_table_add_column        tab_mod_cols  col_set_no_default    number(15)           ""         ""   ""
@@alter_table_add_column        tab_mod_cols  col_set_byte          "varchar2(15 byte)"  mandatory  ""   ""
@@alter_table_add_column        tab_mod_cols  col_set_char          "varchar2(15 char)"  mandatory  ""   ""

@@create_table                  tab_datatypes  ""  ""  ""  ""  ""  ""
@@alter_table_add_column        tab_datatypes  col_number_def        number               ""  ""   ""
@@alter_table_add_column        tab_datatypes  col_number_10         number(10)           ""  ""   ""
@@alter_table_add_column        tab_datatypes  col_number_14_3       number(14,3)         ""  ""   ""
@@alter_table_add_column        tab_datatypes  col_blob              blob                 ""  ""   ""
@@alter_table_add_column        tab_datatypes  col_clob              clob                 ""  ""   ""
@@alter_table_add_column        tab_datatypes  col_nclob             nclob                ""  ""   ""
@@alter_table_add_column        tab_datatypes  col_varchar2_10       varchar2(10)         ""  ""   ""
@@alter_table_add_column        tab_datatypes  col_varchar2_10b      "varchar2(10 byte)"  ""  ""   ""
@@alter_table_add_column        tab_datatypes  col_varchar2_10c      "varchar2(10 char)"  ""  ""   ""
@@alter_table_add_column        tab_datatypes  col_nvarchar2_10      nvarchar2(10)        ""  ""   ""
@@alter_table_add_column        tab_datatypes  col_char_1            char(1)              ""  ""   ""
@@alter_table_add_column        tab_datatypes  col_char_def          char                 ""  ""   ""
@@alter_table_add_column        tab_datatypes  col_date              date                 ""  ""   ""
@@alter_table_add_column        tab_datatypes  col_xmltype           xmltype              ""  ""   ""
@@alter_table_add_column        tab_datatypes  col_timestamp_def     timestamp            ""  ""   ""
@@alter_table_add_column        tab_datatypes  col_timestamp_6       timestamp(6)         ""  ""   ""
@@alter_table_add_column        tab_datatypes  col_timestamp_9       timestamp(9)         ""  ""   ""
@@alter_table_add_column        tab_datatypes  col_timestamp_def_timezone     timestamp_with_time_zone      ""  ""   ""
@@alter_table_add_column        tab_datatypes  col_timestamp_6_timezone       timestamp_with_time_zone(6)   ""  ""   ""
@@alter_table_add_column        tab_datatypes  col_timestamp_9_timezone       timestamp_with_time_zone(9)   ""  ""   ""
@@alter_table_add_column        tab_datatypes  col_rowid             rowid                ""  ""   ""
@@alter_table_add_column        tab_datatypes  col_raw               raw(10)              ""  ""   ""
@@alter_table_add_column        tab_datatypes  col_float_2           float(2)             ""  ""   ""
@@alter_table_add_column        tab_datatypes  col_float_def         float                ""  ""   ""
@@alter_table_add_column        tab_datatypes  col_with_num_#        number               ""  ""   ""

@@create_table                  tab_long  ""  ""  ""  ""  ""  ""
@@alter_table_add_column        tab_long  col_number  number  ""  ""  ""
@@alter_table_add_column        tab_long  col_long    long    ""  ""  ""

@@create_table                  tab_long_raw  ""  ""  ""  ""  ""  ""
@@alter_table_add_column        tab_long_raw  col_number    number      ""  ""  ""
@@alter_table_add_column        tab_long_raw  col_long_raw  "long raw"  ""  ""  ""


