CREATE TABLE TAB_CREATE
(
  ID NUMERIC(15) NOT NULL
);

CREATE TABLE TAB_INS_COL
(
  ID NUMERIC(15) NOT NULL,
  NEW_COL NUMERIC(15) DEFAULT 66 NOT NULL
);

INSERT INTO TAB_INS_COL
       (
       ID,
       NEW_COL
       )
VALUES (
       5,
       66
       );

CREATE TABLE TAB_DEL_COL
(
  ID NUMERIC(15) NOT NULL
);

CREATE TABLE TAB_MOD_COLS
(
  COL_CHG_PRECISION     NUMERIC(15,6)       NOT NULL,
  COL_SET_NULLABLE      VARCHAR(15),
  COL_SET_NOT_NULLABLE  VARCHAR(15)       NOT NULL,
  COL_SET_DEFAULT       NUMERIC(15) DEFAULT 4,
  COL_CHG_DEFAULT       NUMERIC(15) DEFAULT 7,
  COL_SET_NO_DEFAULT    NUMERIC(15),
  COL_SET_BYTE          VARCHAR(15)  NOT NULL,
  COL_SET_CHAR          VARCHAR(15)  NOT NULL,
  COL_CHG_SIZE          NUMERIC(14)         NOT NULL,
  COL_CHG_TYPE          VARCHAR(15)       NOT NULL,
  COL_INC_PRECISION_DEF NUMERIC(5,2)   CONSTRAINT def_test3  DEFAULT 0
);

CREATE TABLE TAB_DATATYPES
(
  COL_NUMBER_DEF NUMERIC,
  COL_NUMBER_10 NUMERIC(10),
  COL_NUMBER_14_3 NUMERIC(14,3),
  COL_BLOB VARBINARY(MAX),
  COL_CLOB VARCHAR(MAX),
  COL_VARCHAR2_10 VARCHAR(10),
  COL_VARCHAR2_10B VARCHAR(10),
  COL_VARCHAR2_10C VARCHAR(10),
  COL_CHAR_1 CHAR(1),
  COL_CHAR_DEF CHAR,
  COL_DATE DATE,
  COL_XMLTYPE XML,
  COL_TIMESTAMP_DEF DATETIME2  ,
  COL_TIMESTAMP_6 DATETIME2(6) ,
  COL_TIMESTAMP_DEF_TIMEZONE DATETIMEOFFSET ,
  COL_TIMESTAMP_6_TIMEZONE DATETIMEOFFSET(6) ,
  COL_RAW VARBINARY(10),
  COL_FLOAT_DEF FLOAT(53),
  COL_WITH_NUM_# NUMERIC,
  COL_INTEGER INTEGER
);

CREATE TABLE TAB_DATAYPE_CONVERSION
(
  COL_NUMBER_TO_VARCHAR2    VARCHAR(15)   NOT NULL,
  COL_VARCHAR2_TO_NUMBER    NUMERIC(15)     NOT NULL,
  COL_CHAR_TO_VARCHAR2      VARCHAR(1)    NOT NULL,
  COL_VARCHAR2_TO_CHAR      CHAR(1)        NOT NULL,
  COL_CLOB_TO_VARCHAR2      VARCHAR(15)   NOT NULL,
  COL_VARCHAR2_TO_CLOB      VARCHAR(MAX)           NOT NULL
);
INSERT INTO TAB_DATAYPE_CONVERSION
(
  COL_NUMBER_TO_VARCHAR2,
  COL_VARCHAR2_TO_NUMBER,
  COL_CHAR_TO_VARCHAR2,
  COL_VARCHAR2_TO_CHAR,
  COL_CLOB_TO_VARCHAR2,
  COL_VARCHAR2_TO_CLOB
)
VALUES
(
  '1',
  2,
  '3',
  '4',
  '5',
  '6'
);

