CREATE TABLE TAB_INS_COL
(
  ID NUMERIC(15) NOT NULL
);

INSERT INTO TAB_INS_COL
       (
       ID
       )
VALUES (
       5
       );

CREATE TABLE TAB_DEL_COL
(
  ID NUMERIC(15) NOT NULL,
  NEW_COL NUMERIC(15) NOT NULL
);

CREATE TABLE TAB_DROP_ME
(
  ID NUMERIC(15) NOT NULL
);

CREATE TABLE TAB_MOD_COLS
(
  COL_CHG_SIZE          NUMERIC(15)         NOT NULL,
  COL_CHG_PRECISION     NUMERIC(15)         NOT NULL,
  COL_CHG_TYPE          NUMERIC(15)         NOT NULL,
  COL_SET_NULLABLE      VARCHAR(15)         NOT NULL,
  COL_SET_NOT_NULLABLE  VARCHAR(15),
  COL_SET_DEFAULT       NUMERIC(15),
  COL_CHG_DEFAULT       NUMERIC(15)  CONSTRAINT def_test1 DEFAULT 6,
  COL_SET_NO_DEFAULT    NUMERIC(15)  CONSTRAINT def_test2  DEFAULT 5,
  COL_SET_BYTE          VARCHAR(15)  NOT NULL,
  COL_SET_CHAR          VARCHAR(15)  NOT NULL
);


CREATE TABLE TAB_DATAYPE_CONVERSION
(
  COL_NUMBER_TO_VARCHAR2    NUMERIC(15)     NOT NULL,
  COL_VARCHAR2_TO_NUMBER    VARCHAR(15)   NOT NULL,
  COL_CHAR_TO_VARCHAR2      CHAR(1)        NOT NULL,
  COL_VARCHAR2_TO_CHAR      VARCHAR(1)    NOT NULL,
  COL_CLOB_TO_VARCHAR2      VARCHAR(MAX)           NOT NULL,
  COL_VARCHAR2_TO_CLOB      VARCHAR(15)   NOT NULL,
);
INSERT INTO TAB_DATAYPE_CONVERSION
(
  COL_NUMBER_TO_VARCHAR2,
  COL_VARCHAR2_TO_NUMBER,
  COL_CHAR_TO_VARCHAR2,
  COL_VARCHAR2_TO_CHAR,
  COL_CLOB_TO_VARCHAR2,
  COL_VARCHAR2_TO_CLOB
)
VALUES
(
  1,
  '2',
  '3',
  '4',
  '5',
  '6'
);

